"""initial schema

Revision ID: 4acc9d5f6339
Revises: 
Create Date: 2026-08-20 00:53:48.883002

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4acc9d5f6339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_catalog_items_id'), 'catalog_items', ['id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('functional_items', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('unit_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_he', sa.String(), nullable=True),
    sa.Column('can_view_all_equipment', sa.Boolean(), nullable=True),
    sa.Column('can_view_battalion_inventory', sa.Boolean(), nullable=True),
    sa.Column('can_view_battalion_realtime', sa.Boolean(), nullable=True),
    sa.Column('can_view_company_realtime', sa.Boolean(), nullable=True),
    sa.Column('can_change_maintenance_status', sa.Boolean(), nullable=True),
    sa.Column('can_mark_as_defective', sa.Boolean(), nullable=True),
    sa.Column('can_assign_equipment', sa.Boolean(), nullable=True),
    sa.Column('can_change_assignment_others', sa.Boolean(), nullable=True),
    sa.Column('can_assign_roles', sa.Boolean(), nullable=True),
    sa.Column('can_add_category', sa.Boolean(), nullable=True),
    sa.Column('can_add_specific_item', sa.Boolean(), nullable=True),
    sa.Column('can_remove_category', sa.Boolean(), nullable=True),
    sa.Column('can_remove_specific_item', sa.Boolean(), nullable=True),
    sa.Column('can_manage_locations', sa.Boolean(), nullable=True),
    sa.Column('can_generate_battalion_report', sa.Boolean(), nullable=True),
    sa.Column('can_generate_company_report', sa.Boolean(), nullable=True),
    sa.Column('holds_equipment', sa.Boolean(), nullable=True),
    sa.Column('must_report_presence', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('solution_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_solution_types_id'), 'solution_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('battalion', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('unit_path', sa.String(), nullable=True),
    sa.Column('unit_hierarchy', sa.String(), nullable=True),
    sa.Column('is_active_duty', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_personal_number'), 'users', ['personal_number'], unique=True)
    op.create_index(op.f('ix_users_unit_hierarchy'), 'users', ['unit_hierarchy'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sensitivity', sa.String(), nullable=True),
    sa.Column('unit_hierarchy', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_location_id', sa.Integer(), nullable=True),
    sa.Column('holder_user_id', sa.Integer(), nullable=True),
    sa.Column('custom_location', sa.String(), nullable=True),
    sa.Column('actual_location_id', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actual_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['holder_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_unit_hierarchy'), 'equipment', ['unit_hierarchy'], unique=False)
    op.create_table('fault_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fault_types_id'), 'fault_types', ['id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('fault_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['fault_type_id'], ['fault_types.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('involved_user_id', sa.Integer(), nullable=True),
    sa.Column('involved_location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_status_at_time', sa.Boolean(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('is_returned_broken', sa.Boolean(), nullable=True),
    sa.Column('broken_description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['involved_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['involved_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_logs_id'), 'transaction_logs', ['id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(), nullable=False),
    sa.Column('reported_status', sa.String(), nullable=False),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_table('equipment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_status_history_id'), 'equipment_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_status_history_id'), table_name='equipment_status_history')
    op.drop_table('equipment_status_history')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_transaction_logs_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_fault_types_id'), table_name='fault_types')
    op.drop_table('fault_types')
    op.drop_index(op.f('ix_equipment_unit_hierarchy'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_users_unit_hierarchy'), table_name='users')
    op.drop_index(op.f('ix_users_personal_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_solution_types_id'), table_name='solution_types')
    op.drop_table('solution_types')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_catalog_items_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
